### ISSUE TITLE
incorrectly gives errors for XHTML

### ISSUE THREAD

**Issue by garretwilson** [yaniswang/HTMLHint#102]
If I have an XHTML file (HTML stored as XML), specifically, HTML5, my file starts like this:

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html><html  lang="en-us"  xmlns="http://www.w3.org/1999/xhtml">

Unfortunately HTMLHint thinks that `<` must be escaped, that a DOCTYPE must appear before it, etc. This will confuse my translators. Can HTMLHint accept valid XML intro information?

**Comment by yaniswang** [comment]
HTMLHint only support HTML code, xml is not supported.

**Comment by garretwilson** [comment]
Please, do you understand that XHTML _is_ a type of HTML? I'm not talking about any old XML. I'm talking about XHTML, which is HTML that is extra-strict. Sure, the XHTML will have namespaces, but as far as HTMLHint is concerned those are just attributes.

See http://www.w3.org/TR/html5/introduction.html#html-vs-xhtml for more information.

So that only leaves us really with the XML declaration. Your tool simply needs to recognize that the first line may be an XML declaration. Why is that such a bad thing? Why must your tool prohibit an XML declaration for an XHTML file? If you would only allow a way for us not to consider the XML declaration an error. That is the main problem here.

**Comment by yaniswang** [comment]
Why add `<?xml version="1.0" encoding="utf-8"?>` at front?

**Comment by waldyrious** [comment]
@garretwilson I suggest using [polyglot (x)html5](https://en.wikipedia.org/wiki/Polyglot_markup). HtmlHint is able to deal with .xhtml files since #34; I have it set up at [browserpad](https://github.com/browserpad/browserpad) for instance (see the [htmlhint.conf](https://github.com/browserpad/browserpad/blob/gh-pages/htmlhint.conf)). It doesn't check all of xhtml's requirements, but it covers most of it, I believe. of course, additional rules for stricter validation would be great :)

**Comment by garretwilson** [comment]
@yaniswang , the XML declaration signals to a processor that they should maintain the strictness of XML. Everybody says their tools support strict HTML structure, but everybody lies (as Dr. House would say). I want one more indication so that the documents won't suddenly end up with `<br>` or unescaped `<` in the middle of `<pre><code>` blocks (e.g. BlueGriffon editor).

I just want HTML5 that is valid XML. For the simple content I'm working with, this would also be valid HTML, so I don't see why this tool dies goes hysterical (hyperbole) when it sees an XML declaration.

**Comment by yaniswang** [comment]
I'm sorry, i have no idea how to check xml.

HTMLHint is a hint tool, only found some useful errors.

It is different from W3C checker.

**Comment by garretwilson** [comment]
@yaniswang , your tool seems very helpful except for this big stumbling block. It's just a simple XML declaration; see https://stackoverflow.com/a/16601746/421049 for example.

If I could get one of my company's developers to fix this (or do it myself) and submit a pull request, would you consider including it?
