### ISSUE TITLE
Read file list from a file

### ISSUE THREAD

**Issue by radek-holy** [yaniswang/HTMLHint#104]
I just realized that there is no cross-platform way to use environment variables in NPM scripts. So, I guess that the only way to have a single source of file patterns is to store them in a file. Can you please consider adding a support to read the patterns from files? I would prefer a simple text file over e.g. a JSON file.

**Comment by yaniswang** [comment]
You can use --ignore, such as:

	htmlhint --ignore **/build/**,**/test/**
