### ISSUE TITLE
Ignore a single HTML file

### ISSUE THREAD

**Issue by Zorgatone** [yaniswang/HTMLHint#109]
Hi,

I'm wondering how can I ignore a single HTML file? Is there a .htmlhintrc option or an HTML rule comment I can use, to suppress all warnings/errors from that single file?

Thanks

**Comment by yaniswang** [comment]
htmlhint -h
	htmlhint --ignore **/build/**,**/test/**

**Comment by Zorgatone** [comment]
I'm using it along with the atom editor. Is there any way to ignore a file without the command line?
I'd like to know if I can do that with a .htmlhintrc option or an HTML rule comment

**Comment by yaniswang** [comment]
Then you can send issue to atom htmlhint plugin.

**Comment by Zorgatone** [comment]
Usually other linters handle this case, not their atom plugins

**Comment by yaniswang** [comment]
HTMLHint core only hint one file, it can't support for ignore files.

The ignore feature must develop out core.
