### ISSUE TITLE
Wrong error in datalist tag

### ISSUE THREAD

**Issue by ChristosKon** [yaniswang/HTMLHint#110]
The default structure of the HTML datalist element `<datalist>`, contains `<option>` elements without closing tags (Reference: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist), [W3C](https://www.w3.org/TR/html5/forms.html#the-datalist-element)).

HTMLHint shows a wrong error:
<img width="620" alt="screen shot 2016-02-08 at 01 52 40" src="https://cloud.githubusercontent.com/assets/6293460/12876253/c84bc9b6-ce06-11e5-9bc0-58058e944288.png">

**Comment by waldyrious** [comment]
If you have the "tag-pair" option checked, the error is justified. If this tool overrode that setting, then one couldn't use it to enforce e.g. xhtml well-formedness. Self-closing the tag with `<option ... />` correctly fixes the error if tag-pair is enabled -- the alternative is simply disabling that check.
