### ISSUE TITLE
<wbr> not paired

### ISSUE THREAD

**Issue by Mottie** [yaniswang/HTMLHint#111]
When I test the following HTML

```html
<span>1/<wbr>2</span>
```

HTMLHint shows this message:

    Tag must be paired, missing: [ </wbr> ], start tag match failed [ <wbr> ] on line 8.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) usage context:

    Tag omission - It is an empty element; it must have a start tag, but must not have an end tag.

**Comment by waldyrious** [comment]
This is pretty much the same issue as #110.

**Comment by yaniswang** [comment]
Can you show me the browser name and version whol support this tag?
I test failed with Chrome 49 and Firefox 44:

http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_wbr
