### ISSUE TITLE
Who uses HTMLHint / Standard (Default) Rules

### ISSUE THREAD

**Issue by gaurav21r** [yaniswang/HTMLHint#112]
For other linters like eslint we have a whole lot of "default" configurations:
AirBNB, Standard JS, Idiomatic JS, etc (https://github.com/rcorp/standard-project-structure/issues/6)

I wanted to know if there is any "standard" configuration options for HTMLHint?

Also usually, projects usually have a "Use in Wild" or "Who uses HTMLHint". We can just open an Issue and invite people to open a PR to add their organisation / project.

I thought I'd request some projects focused on HTML to have an `.htmlhintrc` file.

Tracking request to Polymer here https://github.com/Polymer/polymer/issues/3490
Tracking request to HTML5 Boilerplate here https://github.com/h5bp/html5-boilerplate/issues/1801

**Comment by yaniswang** [comment]
If rules is undefined, it will use default ruleset: https://github.com/yaniswang/HTMLHint/wiki/Usage#about-rules

**Comment by gaurav21r** [comment]
@yaniswang THanks for your response. How about the second part of the question? If you look at other linters, the section on **Who uses this?** or **Use in the wild** will increase adoption (and therefore increase collaboration) of this project? I think ther's no harm if you officially include this in the README, open a PR for this etc.

**Comment by yaniswang** [comment]
Done: https://github.com/yaniswang/HTMLHint/commit/439afc345303caf1f39db9438cbd7759f8c5a80c
