### ISSUE TITLE
Don't validate underscore template tags

### ISSUE THREAD

**Issue by nokru73** [yaniswang/HTMLHint#116]
```
<div id="chaIdentity" class="row no-gutters">
	<%identity%>
</div>
```

underscore template tag starts with <% and ends with %>

**Comment by shaochuancs** [comment]
According to @yaniswang 's answer in #118 : "HTMLHint only support pure html, no support for template."

**Comment by yaniswang** [comment]
You can hide template in script:

	<script type="text/template">
		{{template cmd}}
	</script>
