### ISSUE TITLE
Ignore {{template cmd}}

### ISSUE THREAD

**Issue by johanfo** [yaniswang/HTMLHint#118]
I have  found no way of making HTML lint ignore these kind of templates, frequently used in languages like Go.

<tr {if x}class="warning"{end} >

Is there a way, and if not, should there be a way to ignore it?

**Comment by shaochuancs** [comment]
Could you paste the template code fragment and error message? Not familiar with Go template...

**Comment by johanfo** [comment]
![image](https://cloud.githubusercontent.com/assets/9036091/14105557/98f8df96-f5ac-11e5-8fc1-e37383329085.png)

**Comment by yaniswang** [comment]
HTMLHint only support pure html, no support for template.

**Comment by yaniswang** [comment]
You can hide template in script:

	<script type="text/template">
		{{template cmd}}
	</script>
