### ISSUE TITLE
Rules Wiki: attr unsafe chars example same for good/bad

### ISSUE THREAD

**Issue by JSMike** [yaniswang/HTMLHint#120]
The wiki page: https://github.com/yaniswang/HTMLHint/wiki/attr-unsafe-chars
Has an identical example for good and bad. Can someone please update the examples so that they're distinct? 

I haven't dug in enough to be sure, but from the regex rule I can assume that it would be something for bad like:
`<li><a href="https://vimeo.com/album/1951235/video/56931059‎\u0009">Sud Web 2012</a></li>` 

Can someone please confirm?

It's possible that markdown removed the escaped characters from the bad example. Be sure to use code syntax so it stays.

**Comment by yaniswang** [comment]
fixed: https://github.com/yaniswang/HTMLHint/wiki/attr-unsafe-chars

Tks
