### ISSUE TITLE
Native attribute bindings shows up as an error

### ISSUE THREAD

**Issue by VikramTiwari** [yaniswang/HTMLHint#131]
for example:
`<img src$="{{image}}">` shows up as error message `Special characters must be escaped : [ < ]`

![screen shot 2016-05-01 at 12 15 23 am](https://cloud.githubusercontent.com/assets/1330677/14940607/dbc425c6-0f31-11e6-82ff-5ed613c68790.png)

Also mentioned here: https://github.com/AtomLinter/linter-htmlhint/issues/94

**Comment by yaniswang** [comment]
The issue is allready fixed: https://github.com/yaniswang/HTMLHint/commit/b6a4d1a41994933bf183729c19ee61a32c872921
