### ISSUE TITLE
0.9.13 fails: Object #<Object> has no method 'parse'

### ISSUE THREAD

**Issue by joeyparrish** [yaniswang/HTMLHint#132]
I'm running `./node_modules/.bin/htmlhint demo/index.html`

No problem with the same .htmlhintrc in 0.9.12.

.htmlhintrc is
```json
{
    "alt-require": true,
    "attr-lowercase": false,
    "attr-no-duplication": true,
    "attr-unsafe-chars": true,
    "attr-value-double-quotes": true,
    "attr-value-not-empty": false,
    "csslint": false,
    "doctype-first": true,
    "doctype-html5": true,
    "head-script-disabled": false,
    "href-abs-or-rel": false,
    "id-class-ad-disabled": true,
    "id-class-value": true,
    "id-unique": true,
    "inline-script-disabled": true,
    "inline-style-disabled": true,
    "jshint": false,
    "space-tab-mixed-disabled": true,
    "spec-char-escape": true,
    "src-not-empty": true,
    "style-disabled": true,
    "tag-pair": true,
    "tag-self-close": false,
    "tagname-lowercase": true,
    "title-require": true
}
```

Output is
```
/home/joeyparrish/hacking/shaka/js/node_modules/htmlhint/bin/formatter.js:30
        var fileInfo = path.parse(file);
                            ^
TypeError: Object #<Object> has no method 'parse'
    at /home/joeyparrish/hacking/shaka/js/node_modules/htmlhint/bin/formatter.js:30:29
    at Array.forEach (native)
    at loadFormatters (/usr/local/google/home/joeyparrish/hacking/shaka/js/node_modules/htmlhint/bin/formatter.js:29:14)
    at Object.<anonymous> (/usr/local/google/home/joeyparrish/hacking/shaka/js/node_modules/htmlhint/bin/formatter.js:11:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by yaniswang** [comment]
What's your node version?

**Comment by joeyparrish** [comment]
`node -v` says `v0.10.25`

**Comment by yaniswang** [comment]
Can you debug the code in your node?

Found why `require('path')` have no parse method.

**Comment by joeyparrish** [comment]
This is what `path` looks like:

```js
path { resolve: [Function],
  normalize: [Function],
  join: [Function],
  relative: [Function],
  sep: '/',
  delimiter: ':',
  dirname: [Function],
  basename: [Function],
  extname: [Function],
  exists: [Function: deprecated],
  existsSync: [Function: deprecated],
  _makeLong: [Function] }
```

I will keep digging.

**Comment by joeyparrish** [comment]
It appears this was introduced in v0.12.  Do you intend to support v0.10?  That is the version shipped with Ubuntu 14 (LTS) and 15.

If you only support v0.12, you should add an ["engines" section](https://docs.npmjs.com/files/package.json#engines) to your package.json to make it clear that your package now requires this.

**Comment by joeyparrish** [comment]
You may also be able to depend on this polyfill for `path.parse`: https://www.npmjs.com/package/path-parse

**Comment by joeyparrish** [comment]
I can confirm that along with a dependence on 'path-parse', this change in formatter.js fixes it for me:

```js
var path = require('path');
var events = require('events');
var glob = require('glob');
path.parse = path.parse || require('path-parse');
```

**Comment by yaniswang** [comment]
No way to upgrade node version?

**Comment by joeyparrish** [comment]
I can upgrade node on my workstation, but that doesn't really help if your package doesn't declare its dependency on node v0.12.  People can still clone my project, which depends on htmlhint, try to build it, then get a confusing failure from htmlhint.  So until this is fixed, I had to set my project to require v0.9.12 of htmlhint.

Either declaring a dependence on node v0.12 or using the path-parse polyfill would help, in my opinion.  I would prefer the polyfill, because it means htmlhint running in more places.  Either fix would be technically correct, though.

**Comment by joeyparrish** [comment]
Thank you very much!

**Comment by yaniswang** [comment]
Wait next release.

**Comment by joeyparrish** [comment]
@yaniswang, any idea when the next release will be?

**Comment by joeyparrish** [comment]
@yaniswang, will there be a new release any time soon?

**Comment by joeyparrish** [comment]
Still no new release?  0.9.12 was missing a feature I needed and 0.9.13 broke support for node v0.10.  You've already fixed all the issues I care about.  Now I just need 0.9.14 released on npm so I can depend on it and use it in my project.
