### ISSUE TITLE
Attribute validation rules fails inside Handlebars expressions

### ISSUE THREAD

**Issue by eugenet8k** [yaniswang/HTMLHint#134]
It seems after the last v0.9.13 the handlebars expressions `{{some expression}}` within a tag are being validated. Which leads to big amount more-or-less irrelevant to html validation exceptions, like:

attr-value-double-quotes:
```
app/templates/some-template.hbs
      L1 |<span {{qe id='icon-type' value=type}}>{{icon type_icon}}</span>
                    ^ The value of attribute [ id ] must be in double quotes. (attr-value-double-quotes)
      L1 |<span {{qe id='icon-type' value=type}}>{{icon type_icon}}</span>
                                       ^ The value of attribute [ value ] must be in double quotes. (attr-value-double-quotes)
```

attr-lowercase:
```
   app/templates/_partials/_selectOption.hbs
      L1 |<option value="{{value}}" {{isSelected}}>{{text}}</option>
                                   ^ The attribute name of [ {{isSelected}} ] must be in lowercase. (attr-lowercase)
```

I guess htmlhint shouldn't validate anything within `{{ }}`. Just wondering if it's an expected behavior or regression? It used to work fine before the last release.

**Comment by yaniswang** [comment]
HTMLHint only support HTML code, no support to template code.

**Comment by yaniswang** [comment]
<%if>
		<div>
	<%else%
		<div>
	<%end%>
	</div>

How to hint this code?

**Comment by eugenet8k** [comment]
@yaniswang I don't think there is an expectation for htmlhint to validate the syntax of Handlebars expression but rather to not interfere with them as it seems to have been working till now.

Do you think there are any ways around this particular problem? Maybe by adding some custom rule handler that would extend existing htmlhint logic and disable it for this example.

**Comment by yaniswang** [comment]
Template code must render to html, then use HTMLHint to scan it.

**Comment by eugenet8k** [comment]
@yaniswang yes, you are right. It may be hard to render templates during grunt builds though. I think I will try to pass hbs markup files through regexp like

```html = html.replace(/{{.*}}/g, '')```

before checking them with htmlhint.

Maybe it would be a decent feature for htmlhint at some point. To add a filter parameter with regexp that strips off all the template-related stuff like <% .. %> or {{ ... }}. It seems a lot of people stumble upon this use case with htmlhint.

Thanks for all the work on this amazing project!

**Comment by yaniswang** [comment]
Your idea is bad.

	{{if}}
		<div>
	{{else}}
		<div>
	{{end}}
	</div>

If you cover `{{}}` to blank.

	<div>
	<div>
	</div>
	
HTMLHint will report `Tag must be paired.`

**Comment by eugenet8k** [comment]
@yaniswang well, I have been using htmlhint with my templates with this config:

```
{
  "tagname-lowercase": true,
  "attr-lowercase": true,
  "attr-value-double-quotes": true,
  "doctype-first": false,
  "tag-pair": false,
  "spec-char-escape": false,
  "id-unique": true,
  "src-not-empty": true,
  "attr-no-duplication": true,
  "title-require": false
}
```

`tag-pair` won't work with stripped templates, you are correct. But the rest of the checks for attributes and quotes work just fine and it is a big help.

**Comment by eugenet8k** [comment]
To whoever stuck with the same issue of failing htmlhint inside template expressions like `<% ... %>` or `{{ ... }}`. If you use grunt, this combination may work. You need to install `grunt-string-replace, grunt-contrib-clean` and then with gruntfile like

```
    'string-replace':
      'hbs-strip':
        files:
          'tmp/': 'app/templates/**/*.hbs'
        options:
          replacements:
            [{pattern: /{{.*}}/g, replacement: ''}]

    htmlhint:
      options:
        htmlhintrc: '.htmlhintrc'
      html:
        src: ['tmp/app/templates/**/*.hbs']

    clean:
      'hbs-strip':
        src: 'tmp/*'
```
 run

`grunt string-replace:hbs-strip htmlhint clean`

get

```
Running "string-replace:hbs-strip" (string-replace) task

Running "htmlhint:html" (htmlhint) task
>> 98 files lint free.

Running "clean:hbs-strip" (clean) task
>> 1 path cleaned.
```
