### ISSUE TITLE
spec-char-escape: why does ">" raise an error?

### ISSUE THREAD

**Issue by kaelig** [yaniswang/HTMLHint#139]
``` html
<div>&lt;div></div>
```

This is an acceptable syntax, should it really raise an error?

**Comment by yaniswang** [comment]
http://htmlhint.com/

![image](https://cloud.githubusercontent.com/assets/970390/15278552/dedb2c92-1b4c-11e6-93e3-d8c5a6358f14.png)

**Comment by kaelig** [comment]
@yaniswang thanks for posting this screenshot. Some characters should definitely be encoded because they can be harmful (`<` is the main one), but `>` seems inoffensive, unless I'm missing a use case?

**Comment by yaniswang** [comment]
We hint the code, security is not the main purpose.
`<` must encode, `>` also must encode.

**Comment by kaelig** [comment]
I understand. Unfortunately [one of the HTML transformations](http://prismjs.com/) I'm applying to my code doesn't encode `>`. Could there be an option that would allow a whitelist of chars to not raise errors?

**Comment by yaniswang** [comment]
Just confirm your code is bad or not?
I support `>` must encode.

**Comment by kaelig** [comment]
> I support `>` must encode.

Ok, maybe there could be another rule. It would check that `<` are encoded in `<pre>` and `<code>` tags.

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
