### ISSUE TITLE
Malformed attributes not detected

### ISSUE THREAD

**Issue by shanavas786** [yaniswang/HTMLHint#145]
Htmlhint doesn't detect malformed attributes like
```
 <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" {{$index + 1}}></button>

```

`{{$index+1}}` is not a valid html attribute. But its not reported by htmlhint.

**Comment by yaniswang** [comment]
It is no problem.

` {{$indDex + 1}}` will format to 3 attrs:

`{{$indDex`
`+`
`1}}`

**Comment by shanavas786** [comment]
Went through w3.org specifications. Thanks
