### ISSUE TITLE
Do I need to setup HtmlHit to work with Angular 2 templates?

### ISSUE THREAD

**Issue by GoshaFighten** [yaniswang/HTMLHint#169]
I have a template file like this:

```
<div *ngFor="let item of items" (click)="helloWorld()">
    Test
</div>
```

When I run `htmlhint`, I see the following errors:

![2016-09-07_0128](https://cloud.githubusercontent.com/assets/10522139/18293275/78297a1a-749a-11e6-9c3b-40d9bad82b9d.png)

See [these pull requests](https://github.com/yaniswang/HTMLHint/pulls?utf8=%E2%9C%93&q=angular). But, it's not clear if I need to customize some settings.

My `htmlhint` version is 0.9.13.

**Comment by yaniswang** [comment]
HTMLHint is no supported for template code.
