### ISSUE TITLE
custom rule doesnt work

### ISSUE THREAD

**Issue by miukki** [yaniswang/HTMLHint#171]
![image](https://cloud.githubusercontent.com/assets/132497/18355833/fdab1878-761c-11e6-9930-bc2546fbad76.png)

```
var HTMLHint  = require('htmlhint').HTMLHint;

module.exports = function(HTMLHint) {
    HTMLHint.addRule({
        id: 'test-rule',
        description: 'test rule.',
        init: function(parser, reporter){
            var self = this;

             reporter.warn('Found body.');
       
            parser.addListener('tagstart', function(event){
                var tagName = event.tagName.toLowerCase();
                if(tagName === 'body'){
                    reporter.warn('Found body.', event.line, event.col, self, event.raw);
                }
            });
        }
    });
};

```

error:

TypeError: Cannot read property 'id' of undefined

**Comment by yaniswang** [comment]
Try:

	var HTMLHint  = require('htmlhint').HTMLHint;

	HTMLHint.addRule({
		id: 'test-rule',
		description: 'test rule.',
		init: function(parser, reporter){
			var self = this;

			 reporter.warn('Found body.');

			parser.addListener('tagstart', function(event){
				var tagName = event.tagName.toLowerCase();
				if(tagName === 'body'){
					reporter.warn('Found body.', event.line, event.col, self, event.raw);
				}
			});
		}
	});

**Comment by miukki** [comment]
resolve it . it was because i have added wrong id to .htmlhintrc .
