### ISSUE TITLE
clipPath triggers error but its ok

### ISSUE THREAD

**Issue by mike3run** [yaniswang/HTMLHint#212]
![screen shot 2017-07-20 at 11 42 42 am](https://user-images.githubusercontent.com/7088511/28428933-8fca8570-6d40-11e7-9c03-2fe007c30781.png)

https://developer.mozilla.org/en/docs/Web/SVG/Element/clipPath

🦄

**Comment by mike3run** [comment]
https://github.com/yaniswang/HTMLHint/wiki/Attr-lowercase

Removing because of this, sorry

**Comment by mike3run** [comment]
Maybe tagname lowercase should take an array of exceptions too?

https://github.com/yaniswang/HTMLHint/wiki/Tagname-lowercase

**Comment by hacknug** [comment]
@mike3run check #188 for that
