### ISSUE TITLE
Incorrect "tag must be paired" message

### ISSUE THREAD

**Issue by aroberge** [yaniswang/HTMLHint#23]
I'm using htmlhint as an extension of the Brackets editor.

In a file, I have an audio tag with a source tag:
[audio id="take-sound" preload]
  [source src="src/sounds/pick.wav" type="audio/x-wav"]
[/audio]

I get a "tag must be paired message".  In html5, the source tag does not require a closing tag.

It would be useful if htmlhint would allow the insertion of comments within html5 to disable errors, something like

[!--  htmlhint  ignore:line --]

EDIT: have replace angle brackets by square brackets, otherwise the entire content inside them disappeared.

**Comment by adarrra** [comment]
Hi! Why I get error message from this code?
`<a role="document" ng-href={{"docs/lic_"+currentLang+".txt"}} target="_blank"> {{'LICENSE' | translate}} </a>`

`Tag must be paired, No start tag: [ </a> ]`

**Comment by yaniswang** [comment]
HtmlHint only support html code, no support template.

**Comment by adarrra** [comment]
It's a pity

**Comment by vsjegadeesh** [comment]
@aroberge hey bro, you might have missed the div or any other pair , thats the problem , just now i solved on my own  :+1:

**Comment by jfoclpf** [comment]
@yaniswang please reopen the issue

I get this error on standard HTML5 [`datalist`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) referring that `<option>` must be paired, but it does not

```html
<label for="myBrowser">Choose a browser from this list:</label>
<input list="browsers" id="myBrowser" name="myBrowser" />
<datalist id="browsers">
  <option value="Chrome">
  <option value="Firefox">
  <option value="Internet Explorer">
  <option value="Opera">
  <option value="Safari">
  <option value="Microsoft Edge">
</datalist>
```

**Comment by dphillips479** [comment]
I'm working a lot with TYPO3 and some of it's viewhelpers chain arguments separated by dots in the tag name. This will throw an error:

```html
<f:link.page>
  some text
</f:link.page>
```

It would be nice if HtmlHint would let the `.` slide and I wouldn't have to deactivate tag-pair completely. I know these aren't standard tags. But it would be nice to have an option for these cases.

I would change the rule and load it as a custom one, but I'm not sure how I can make it ignore the dot.
