### ISSUE TITLE
html5+svg attributes are camelCase

### ISSUE THREAD

**Issue by sglaser** [yaniswang/HTMLHint#28]
In SVG, some attributes are camelCase. I'm using Brackets with the HTMLHint extension and HTMLHint flags them as errors. For example, it complains about viewBox in this snippet.

```
<div class="svg hasSVG">
   <svg version="1.1" width="100%" height="194" viewBox="0 0 740 194">
      <g>
         <text x="512" y="12" class="regBitNum">0</text>
          <text x="16" y="12" class="regBitNum">31</text>
          <path d="M520,2l0,16M424,2l0,16M376,2l0,16M360,2l0,16M344,2l0,16M328,2l0,16M312,2l0,16M440,2l0,16M392,2l0,16M296,2l0,16M8,5.333333333333333l0,16" class="regBitNumLine" fill="none"></path>
       </g>
   </svg>
</div>
```

Ideally, HTMLHint would have a list of attributes that are camelCase (that can be extended / controlled by the user). Extra credit if it knows which tags allow which attribute.

**Comment by yaniswang** [comment]
I suggest to choose our own rules set, if i use in HTML5, then you no need to choose attr-lowercase rule.

**Comment by rodrigogoncalves** [comment]
Could it be the case for `tagname-lowercase` rule as well? In the svg world there are tags which are also camel cased. I've noticed that https://github.com/yaniswang/HTMLHint/issues/121 is a one-liner that solves the problem for attributes, perhaps we could use almost the same code for tagname too?

**Comment by hacknug** [comment]
Any plans on merging #188 in?

**Comment by jaepage** [comment]
My HTML document's first line is `<!DOCTYPE html>` (HTML5), but I'm still getting "The attribute name of [ patternUnits ] must be in lowercase" errors.
