### ISSUE TITLE
img-alt-require

### ISSUE THREAD

**Issue by szarouski** [yaniswang/HTMLHint#35]
I believe that 'img-alt-require' should only check cases when alt is not specified. alt attribute could and must be empty in cases when you don't want screen reader to read image description.
Proof: http://blog.silktide.com/2012/12/unnecessary-alt-text/ under So can we just omit the alt tag altogether?, http://osric.com/chris/accidental-developer/2012/01/when-should-alt-text-be-blank/, http://jimthatcher.com/webcourse2.htm under google logo.

Thanks

**Comment by paulsouche** [comment]
Hi,

I think this rule is broken on 0.9.7...

```javascript
   var HTMLHint  = require("htmlhint").HTMLHint;
   var messages = HTMLHint.verify('<img src="myImg"/>', {'img-alt-require': true});
   console.log(messages);

logs on 0.9.5 :
[
  {
    "type": "warning",
    "message": "Alt of img tag must be set value.",
    "raw": "<img src=\"myImg\"/>",
    "evidence": "<img src=\"myImg\"/>",
    "line": 1,
    "col": 1,
    "rule": {
      "id": "img-alt-require",
      "description": "Alt of img tag must be set value.",
      "link": "https://github.com/yaniswang/HTMLHint/wiki/img-alt-require"
    }
  }
]
```

But not on 0.9.7

Create his own rule still work so that's ok for me.

Thanks

**Comment by yaniswang** [comment]
Rule id `img-alt-require` is change to `alt-require`

`<img src="myImg" alt=""/>` is still report no errors.
