### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by oncletom** [yaniswang/HTMLHint#42]
Hello,

for some reason I cannot run `htmlhint` from the command line, either as a global or local install.
Maybe it is related to #21, #40 and #9.

```bash
$ htmlhint src/snippets/sample.html
env: node\r: No such file or directory
```

The following is alright though:

```bash
node node_modules/.bin/htmlhint src/snippets/sample.html
```

Thanks!

**Comment by yaniswang** [comment]
v0.9.8 published: https://www.npmjs.com/package/htmlhint

**Comment by oncletom** [comment]
Ace, thanks @yaniswang :-)
