### ISSUE TITLE
should look in homedir for config like jshint

### ISSUE THREAD

**Issue by MetaMemoryT** [yaniswang/HTMLHint#43]
see:

https://github.com/jshint/jshint/blob/master/src/cli.js#L68

**Comment by lewisl9029** [comment]
I'd like to see this implemented too, along with support for looking for config file in project directory for shared project-specific settings.

**Comment by mattsawyer77** [comment]
what @lewisl9029 said.

**Comment by yaniswang** [comment]
Now is support search default config file in parent directory:
https://github.com/yaniswang/HTMLHint/commit/6a121d77e04e8d59dbfd872ec3a40706bb0a6739
