### ISSUE TITLE
support Polymer <template> syntax

### ISSUE THREAD

**Issue by MetaMemoryT** [yaniswang/HTMLHint#44]
Polymer has new syntax within <template> elements which currently counts as errors.

**Comment by Meligy** [comment]
According to HTML5 spec, http://www.w3.org/TR/html-markup/syntax.html#syntax-attributes the character `?` is (surprisingly) valid HTML5.

Quoting:

>> Attribute names must consist of one or more characters other than the space characters, U+0000 NULL, """, "'", ">", "/", "=", the control characters, and any characters that are not defined by Unicode.

Can we re-open this?

**Comment by Meligy** [comment]
Also from HTML5 specific spec: http://www.w3.org/TR/html5/syntax.html#attributes-0

>  Attribute names must consist of one or more characters other than the space characters, U+0000 NULL, U+0022 QUOTATION MARK ("), U+0027 APOSTROPHE ('), ">" (U+003E), "/" (U+002F), and "=" (U+003D) characters, the control characters, and any characters that are not defined by Unicode. In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of lower- and uppercase letters that are an ASCII case-insensitive match for the attribute's name.

**Comment by gazal-k** [comment]
:+1: Since polymer is working on future HTML5 standards, in my humble opinion this issue is valid.

Also polymer does not use template syntax like this:

```html
{{if}
    <div>
{{else}}
    <div>
{{end}}
</div>
```

It uses template syntax like this:

```html
<template is="dom-if" if="{{condition}}">
  <div>true</div>
</template>
<template is="dom-if" if="{{elseCondition}}">
  <div>false</div>
</template>
```
