### ISSUE TITLE
Csshint and jshint config options should be sub-objects or file references

### ISSUE THREAD

**Issue by JeroMiya** [yaniswang/HTMLHint#46]
The options to run jshint and csshint should themselves be config file references preferably, or at least sub-objects, instead of merging their options into one flat config option:

Referencing a config file:

```json
{
   ...etc...
   "jshint": ".jshintrc"
}
```

Or, as a sub-object:
```json
{
  ...etc...
  "jshint": {
     "eqeqeq": true,
     ...etc...
  }
}
```

I submitted a pull request to add a json schema for the config files:
https://github.com/yaniswang/HTMLHint/pull/45

But I didn't include the schema for the csshint and jshint options. It's not very useful to have all those options in the auto-complete list when you're not using jshint/csshint.

**Comment by yaniswang** [comment]
HTMLHint is allways support .jshintrc file.
And allways support sub-object config.
