### ISSUE TITLE
Custom Rules

### ISSUE THREAD

**Issue by taylor1791** [yaniswang/HTMLHint#47]
Is there any plan to support "custom rules" or allowing users to create rules in addition to the built in ones? For example, adding a rule that detects inline styles and warns on inline styles.

**Comment by yaniswang** [comment]
You can use it like this:

	HTMLHint.addRule({
		id: 'alt-require',
		description: 'Alt of img must be present and alt of area[href] and input[type=image] must be set value.',
		init: function(parser, reporter){
			var self = this;
			parser.addListener('tagstart', function(event){
				var tagName = event.tagName.toLowerCase(),
					mapAttrs = parser.getMapAttrs(event.attrs),
					col = event.col + tagName.length + 1,
					selector;
				if(tagName === 'img' && !('alt' in mapAttrs)){
					reporter.warn('Alt of img tag must be present.', event.line, col, self, event.raw);
				}
				else if((tagName === 'area' && 'href' in mapAttrs) ||
					(tagName === 'input' && mapAttrs['type'] === 'image')){
					if(!('alt' in mapAttrs) || mapAttrs['alt'] === ''){
						selector = tagName === 'area' ? 'area[href]' : 'input[type=image]';
						reporter.warn('Alt of ' + selector + ' must be set value.', event.line, col, self, event.raw);
					}
				}
			});
		}
	});

**Comment by geligelu** [comment]
Hey, where do I use this ``HTML.addrule function?`` - in my Gruntfile?

**Comment by spinnytea** [comment]
@ortonomy there's a blurb about it on the gulp-htmlhint page
https://www.npmjs.com/package/gulp-htmlhint#customrules
