### ISSUE TITLE
Restrict head-script-disabled rule to javascript script tags

### ISSUE THREAD

**Issue by ntdaley** [yaniswang/HTMLHint#49]
As I understand it, the purpose of the `head-script-disabled` rule is to prevent javascript code from suspending rendering of the page while it runs the javascript.
However, javascript is not the only possible use of a script tag.  e.g. AngularJS allows you to inline templates using a script tag with `type="ng-template"`.  https://docs.angularjs.org/api/ng/directive/script

While I generally would want to make sure that my javascript goes as late as possible in the file, I would prefer my inlined angular templates to be in the head element to keep them separate from the main page content.

It would be useful to configure the head-script-disabled rule to ignore script tags with a particular type (e.g. text/ng-template).

e.g. perhaps the configuration could look like:
```json
{
   "head-script-disabled" : {
      "ignore-types" : ["text/ng-template"]
   }
}
```

**Comment by yaniswang** [comment]
It's  done:

https://github.com/yaniswang/HTMLHint/blob/master/src/rules/head-script-disabled.js#L15

**Comment by stokito** [comment]
"prevent javascript code from suspending rendering of the page while it runs the javascript."

But if anyone need to avoid rendering pause they can use `<script defer>` or `<script async>`.
We used head scripts for decades.
The rule is really confusing, especially enabling it by default seems strange for me.

**Comment by coliff** [comment]
> The rule is really confusing, especially enabling it by default seems strange for me.

I agree. We should at least make this rule off by default. I'll make a new issue for that.

**Comment by stokito** [comment]
Sorry, I'm not a profeccinal web dev, maybe I was wrong. Was little bit confused and and worried when tried to figure out how to with the lint error.
I end up by just removed the linter as useless for my project 🤗
