### ISSUE TITLE
command line script should exit non-zero for problems

### ISSUE THREAD

**Issue by focusaurus** [yaniswang/HTMLHint#50]
The script must call `process.exit(1);` with some number between 1 and 255 to enable script and continuous integration systems to understand that problems were found. It currently exits 0 (meaning "success") even when problems are detected.

https://en.wikipedia.org/wiki/Exit_status

**Comment by xi** [comment]
+1

**Comment by yaniswang** [comment]
https://github.com/yaniswang/HTMLHint/blob/master/bin/htmlhint#L123

It's allready done.

**Comment by focusaurus** [comment]
:cake:

**Comment by sahilm** [comment]
Hello @yaniswang -

This code no longer works with node version: `v0.12.2`. `process.stdout.flush()`.

This line: `if ((!process.stdout.flush || !process.stdout.flush()) && (parseFloat(process.versions.node) < 0.5)) {` is always true but the `drain` event is never emitted. `process.stdout.flush()` is undefined.

The process exits with a zero exit code regardless of failures.
