### ISSUE TITLE
JSHint 1.1.0 fails to install behind a proxy

### ISSUE THREAD

**Issue by tokybe** [yaniswang/HTMLHint#51]
I think htmlhint would be more proxy-friendly if you update jshint version to 2.1.3 or newer. Jshint 1.1.0 has a dependency directly from Github (esprima:   https://github.com/ariya/esprima/tarball/master) wich makes htmlhint unusable in my context. I’m maintaining a sonatype nexus private repository for my company, behind a proxy.

**Comment by yaniswang** [comment]
Now fixed.
