### ISSUE TITLE
How to use the jshint and csslint options properly?

### ISSUE THREAD

**Issue by waldyrious** [yaniswang/HTMLHint#56]
I believe I must be doing something wrong, but can't figure out what. Here's what I did: 

    npm install -g htmlhint
    htmlhint -r csslint,jshint index.html

but it always returns "No problem" even if I deliberately introduce erros in the javascript or css. The same errors are detected in http://htmlhint.com/, which is why I know there's got to be something wrong on my side.

What strategy can I use to debug this?

**Comment by yaniswang** [comment]
Suggest this cmd:

	htmlhint -c .htmlhintrc test.html

.htmlhintrc content:

	{
		"jshint": {
			"undef": true
		}
	}

**Comment by waldyrious** [comment]
Thanks for the quick response. If I understand correctly, does that mean that jshint by default won't have any option turned on, so passing `-r jshint` will have no effect? I don't see why anyone would want that. Why not using the [default jshint options](https://github.com/jshint/jshint/blob/master/examples/.jshintrc) in that case?

**Comment by waldyrious** [comment]
Update: jshint will make things clearer in v3.0, according to https://github.com/jshint/jshint/issues/1223. Let's wait and see :)

**Comment by yaniswang** [comment]
I suggest make config clear, choose what user want.
