### ISSUE TITLE
Handling attribute quotes correctly

### ISSUE THREAD

**Issue by aaronpuchert** [yaniswang/HTMLHint#59]
Attribute values can have double quotes `"`, single quotes `'`, or sometimes no quotes at all. Using no quotes though is not recommended. See the [HTML4 standard](http://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2) or the [HTML5 standard](http://www.w3.org/TR/html-markup/spec.html#syntax-attributes).

There has been some discussion about a similar issue (#8), but I think it's OK to complain about using no quotes, although it's technically allowed.

**Comment by yaniswang** [comment]
All rules choiced by your self, so if you want use quotes freely, you don't need to select quotes rules.
