### ISSUE TITLE
Doesn't parse files with .xhtml extension

### ISSUE THREAD

**Issue by waldyrious** [yaniswang/HTMLHint#68]
I can get htmlhint to properly analyze a `test.html` file with the following contents:

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta charset="utf-8" />
    <title>title</title>
  </head>
  <body>
    <p>Lorem ipsum</p>
    <script>
      x = 1;
    </script>
  </body>
</html>
```

And the following .htmlhintrc:

```json
{
    "jshint": {
        "enforceall": true
    }
}
```

Running `htmlhint -c .htmlhintrc test.html` returns, as expected:
```
/home/waldyrious/test.html:
	line 10, col 7: 'x' is not defined.


1 problems.
```

But if I **simply rename the file to `test.xhtml`**, then the command `htmlhint -c .htmlhintrc test.html` returns simply `No problem.`

Given that [test/htmlparser.spec.js](https://github.com/yaniswang/HTMLHint/blob/master/test/htmlparser.spec.js) indicates that it should parse various xhtml flavors, the behavior above seems to be a bug.

**Comment by yaniswang** [comment]
Now is fixed: https://github.com/yaniswang/HTMLHint/pull/34
