### ISSUE TITLE
indent rule

### ISSUE THREAD

**Issue by ficristo** [yaniswang/HTMLHint#73]
For example, I would like to check that indentation of my templates is always 4 spaces.

**Comment by viniciusdacal** [comment]
:+1:

**Comment by kuatsure** [comment]
I would love this as well. trying to get our team to move away from haml ( overly complicated for what we're doing ) to html and the number one thing asked on why people like haml is the enforcement of indention for compilation

**Comment by alex88** [comment]
+1
