### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by devurandom** [yaniswang/HTMLHint#76]
When I try to run `htmlhint`, I get following error message:
```
$ node .npm/htmlhint/0.9.8/package/bin/htmlhint 

module.js:340
    throw err;
          ^
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/AD/tf128/.npm/htmlhint/0.9.8/package/bin/htmlhint:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

```
$ aptitude show nodejs
Package: nodejs                          
State: installed
Automatically installed: yes
Version: 0.10.25~dfsg2-2ubuntu1
Priority: extra
Section: universe/web
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 3,116 k
Depends: libc-ares2 (>= 1.8.0), libc6 (>= 2.14), libssl1.0.0 (>= 1.0.1), libstdc++6 (>= 4.1.1), libv8-3.14.5, zlib1g (>= 1:1.1.4)
Conflicts: nodejs
Description: evented I/O for V8 javascript
 Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run
 across distributed devices. 
 
 Node.js is bundled with several useful libraries to handle server tasks: 
 
 System, Events, Standard I/O, Modules, Timers, Child Processes, POSIX, HTTP, Multipart Parsing, TCP, DNS, Assert, Path, URL, Query Strings.
Homepage: http://nodejs.org/
$ node --version
v0.10.25
$ npm install htmllint
...
htmlhint@0.9.8 node_modules/htmlhint
├── strip-json-comments@1.0.4
├── commander@2.6.0
├── colors@1.0.3
├── csslint@0.10.0 (parserlib@0.2.5)
└── jshint@2.8.0 (exit@0.1.2, shelljs@0.3.0, console-browserify@1.1.0, minimatch@2.0.10, cli@0.6.6, lodash@3.7.0, htmlparser2@3.8.3)
```

I am actually trying to get https://github.com/AtomLinter/linter-htmlhint to work.

**Comment by yaniswang** [comment]
Try to update node to new version v4.1.2, then try reinstall htmlhint again.

npm install htmllint -g

**Comment by devurandom** [comment]
Ok. Do you know of any Ubuntu PPA that has Node v4.1.2 packaged? The only one I found is not much further advanced than Ubuntu Trusty itself.

**Comment by yaniswang** [comment]
It seems your nodejs is not instal well,so the dependencie cannot finded.

**Comment by devurandom** [comment]
My NodeJS installation is just the original package from Ubuntu. I did not modify anything.

**Comment by waldyrious** [comment]
@devurandom according to [this page on nodejs.org](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) there used to be an up-to-date PPA (Chris Lea's), but it's now transitioned into the NodeSource process, which I'm not sure how it works (it seems to be [removing the PPA but not adding a new one](https://github.com/nodesource/distributions/search?q=ppa)). Anyway, if you follow the instructions on the nodejs.org page linked above, it should allow you to update node. You might have to remove your current installation first, or maybe NodeSource takes care of that. Try it out and see if it works for you :)

**Comment by devurandom** [comment]
@waldyrious Thanks! After [installing the current version of NodeJS](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions), uninstalling all modules with `npm uninstall` and `rm -fr ~/.npm`, then reinstalling htmlhint, it appears to work.

**Comment by waldyrious** [comment]
@devurandom great to hear :) you can close this issue then.
