### ISSUE TITLE
Add a --strict option to the command, to activate all available rules

### ISSUE THREAD

**Issue by waldyrious** [yaniswang/HTMLHint#77]
Note: this should combine with the `--config` and the `--rules` options, so that we can, for example, set one rule to false and have the remaining ones set to true, due to `--strict`.

**Comment by waldyrious** [comment]
Btw, this request is similar to what @Satyam suggested on https://github.com/yaniswang/HTMLHint/issues/16#issuecomment-46699012.

**Comment by yaniswang** [comment]
Not all of rules is used for user, some rule is on the contrary of another rule.

**Comment by waldyrious** [comment]
I tried reading through the current list of rules, but couldn't figure out which ones were opposite to other rules. Can you clarify which ones you had in mind?

**Comment by yaniswang** [comment]
Maybe appered in future.

**Comment by waldyrious** [comment]
@yaniswang why close this?

**Comment by yaniswang** [comment]
You can active all rules by your self.
I don't think need to add a optoin.

**Comment by waldyrious** [comment]
For command line usage, for example, it is quite burdensome to activate all rules one by one. I understand that it's not impossible to to right now, but it would be much more convenient with a specific option.

**Comment by yaniswang** [comment]
I just try to develop this feature, i found i have no idea to do it.

Because some rule have special config, 

	{"space-tab-mixed-disabled":"tab"}

**Comment by yaniswang** [comment]
Some rule have no right answer for different user.

**Comment by waldyrious** [comment]
Thanks for looking into it. I suppose using default settings (e.g. tabs by default, in the rule you mention above), which can be overridden using the individual rules, would still be easier to use than specifying all the rules individually, but I understand that the additional complexity may not be desired.

**Comment by yaniswang** [comment]
Not all of rules have right answer for different user.

Such as: https://github.com/yaniswang/HTMLHint/wiki/Id-class-value

All config is ok, or all is not ok.

**Comment by waldyrious** [comment]
> Such as: https://github.com/yaniswang/HTMLHint/wiki/Id-class-value

Not trying to argue here, but that particular rule could have a "html4" and "html5" option (in addition to "underline", "dash" and "hump" and `false`), which would allow all characters allowed by the corresponding HTML4 and HTML5 specs for ID attributes, as described [here](http://stackoverflow.com/a/79022/266309).

**Comment by Shinigami92** [comment]
I want to introduce another way

I will rewrite the config later with a breaking change and then we can support extends like other linters/hinters

```json
{
  "extends": ["htmlhint:recommended"],
  "defaultServerity": "error",
  "rules": {
    "...": [true, {}]
  }
}
```

**Comment by waldyrious** [comment]
Cool. As long as there's a way to easily invoke a preset (and a strict preset is among those available by default in the tool), I'd be happy! :)
