### ISSUE TITLE
Can the command return an error code?

### ISSUE THREAD

**Issue by waldyrious** [yaniswang/HTMLHint#79]
I tried to set this up with Travis but [it doesn't detect](https://travis-ci.org/browserpad/browserpad/builds/84419540) that the command failed, because of:

    The command "htmlhint --config htmlhint.conf index.xhtml" exited with 0.

I suppose [this](https://github.com/yaniswang/HTMLHint/blob/11662db3af8f59e98c9fbd0563118d3b4e91a009/src/core.js#L71) is the line that needs to be adjusted for this to work.

**Comment by yaniswang** [comment]
Fixed, please try again.
https://www.npmjs.com/package/htmlhint

https://travis-ci.org/yaniswang/HTMLHint-test/jobs/84431876

**Comment by waldyrious** [comment]
Confirmed, it works as expected. That was fast, thanks!
