### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by DragorWW** [yaniswang/HTMLHint#83]
There are plans to move to ES6? It would look good here, reducing application code.

**Comment by yaniswang** [comment]
If use ES6, HTMLHint will not compatible old version nodejs？

**Comment by DragorWW** [comment]
You can compile to ES5 or http://blog.andrewray.me/how-to-use-es6-in-nodejs/

**Comment by yaniswang** [comment]
Wait and see for now.
It have not enough reason to use ES6.
