### ISSUE TITLE
[new rule] Max characters per line

### ISSUE THREAD

**Issue by viniciusdacal** [yaniswang/HTMLHint#88]
We could have an option to limit characters per line.

**Comment by tlei123** [comment]
Maybe add this new rule instead to .editorconfig so all files can be handled?  https://github.com/editorconfig/editorconfig/issues?q=is%3Aopen

We face this line-length problem with all files, not just HTML.

**Comment by yaniswang** [comment]
Approve @tlei123 , use editorconfig is better!
