### ISSUE TITLE
Issue using on Polymer Web Components

### ISSUE THREAD

**Issue by opus1269** [yaniswang/HTMLHint#90]
Google's Polymer Web Components use a special nomenclature for binding data to attributes:

https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#attribute-binding

The $ is causing a problem. Its failing the spec-char-escape rule, which makes sense, I think, but it is also failing the tag-pair rule, which should be OK..

Here is a simple example:

```html
<!doctype html>
<html>
<head>
<title>htmlhint issue with Polymer</title>
</head>

<body>
  <div class="setting-label" hidden$="[[!mainLabel]]">{{mainLabel}}</div>
</body>
</html>
```

**Comment by yaniswang** [comment]
HTMLHint only support for pure HTML code, no support for template.
