### ISSUE TITLE
JSHint 'browser' rule won't work

### ISSUE THREAD

**Issue by jakubfiala** [yaniswang/HTMLHint#93]
Hi,

I'm trying to use HTMLHint to check html code with inline JS, and doing it at runtime, just like the demo at the HTMLHint website. However, I can't seem to get the 'browser' rule for jshint to work – therefore, syntax errors are highlighted, but not undefined objects etc.

My options object is as follows:

```
{
  "tagname-lowercase": true,
  "attr-lowercase": true,
  "attr-value-double-quotes": true,
  "doctype-first": false,
  "tag-pair": true,
  "spec-char-escape": true,
  "id-unique": true,
  "src-not-empty": true,
  "attr-no-duplication": true,
  "title-require": false,
  "csslint": {
    "display-property-grouping": true,
    "known-properties": true,
    "empty-rules": true,
    "errors": 2
  },
  "jshint": {
    "browser": true,
    "asi": true
  }
}
```

I'm using HTMLHint 0.9.12.
Any clues as to why this happens?

Cheers,

jakub

**Comment by yaniswang** [comment]
You must include JSHINT and CSSLint in your web page.

**Comment by jakubfiala** [comment]
I did, and both are kind of working – JSHINT successfully returns syntax warnings, e.g. missing semicolons, and I can even turn that option off by specifying `"asi": true` – my question was specifically about the `"browser"` option, so that I can check whether given JS code will execute without errors.

**Comment by yaniswang** [comment]
Can you show me a demo url?

**Comment by jakubfiala** [comment]
Hi Yanis, I actually found out the problem was on JSHINT's side – it doesn't detect the AudioContext object, even though it's standard in all modern browsers already. For all other things, there's the `undef` option. Thanks for your assistance!
