### ISSUE TITLE
`.` in tag attribute causes the tag not to be recognized

### ISSUE THREAD

**Issue by ckaznocha** [yaniswang/HTMLHint#95]
```html
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<title>HTMLHint</title>
</head>
<body>
    <div foo.bar="baz" >HTMLHint: help your html code better</div>
</body>
</html>
```
gives:
```shell
      L8 |    <div foo.bar="baz" >HTMLHint: help your html code better</div>
              ^ Special characters must be escaped : [ < ]. (spec-char-escape)
      L8 |    <div foo.bar="baz" >HTMLHint: help your html code better</div>
                                 ^ Special characters must be escaped : [ > ]. (spec-char-escape)
      L8 |...z" >HTMLHint: help your html code better</div>
                                                     ^ Tag must be paired, no start tag: [ </div> ] (tag-pair)

```

**Comment by yaniswang** [comment]
I don't know the `.` is good or not in w3c?
Who know?

**Comment by waldyrious** [comment]
According to http://www.w3.org/TR/html5/syntax.html#syntax-attributes: 

> Attribute names must consist of one or more characters other than the space characters, U+0000 NULL, U+0022 QUOTATION MARK ("), U+0027 APOSTROPHE ('), ">" (U+003E), "/" (U+002F), and "=" (U+003D) characters, the control characters, and any characters that are not defined by Unicode.

So it looks like `.` is allowed.

**Comment by ckaznocha** [comment]
Came to post the same link as @waldyrious. Just for some color, I using a `.` in an attribute name because an SPA framework's functionality requires it.

**Comment by ccqgithub** [comment]
I am painful to use `vue.js` along with `htmlhint`, but i do not know who is right ……

   template in vue.js 
    <button @click.stop.prevent="doThis"></button>

**Comment by yaniswang** [comment]
@ccqgithub HTMLHint is not suuport for template code.

**Comment by thisconnect** [comment]
I would love if HTMLHint would use a html parser.. like https://www.npmjs.com/package/parse5
It also supports streaming.

**Comment by thisconnect** [comment]
parse5 gives you div `[ { name: 'foo.bar', value: 'baz' } ]` for `<div foo.bar="baz" >`

**Comment by saeidzebardast** [comment]
Same problem in Polymer when using $ in attribute name:
*  ([&lt;/div&gt;] Tag must pair)

```html
<div id$="[[myId]]">
  <content></content>
</div>
```
