### ISSUE TITLE
规则 attr-unsafe-chars 的出发点

### ISSUE THREAD

**Issue by nighca** [yaniswang/HTMLHint#96]
请教一下[这条规则](https://github.com/yaniswang/HTMLHint/wiki/attr-unsafe-chars)存在的考虑是？

为什么`/[\u0000-\u0009\u000b\u000c\u000e-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/`是“unsafe chars” 呢，以及为什么检查仅限于 attribute 的 value 呢

**Comment by yaniswang** [comment]
你那边碰到什么情况了吗？
这条规则是国外提上来的issue。

可以用来检测那些看不见的字符，之前国外那个场景是用来防止出现URL打不开

**Comment by nighca** [comment]
噢情况倒没，就是好奇。

所以其实是不可见字符咯，我以为这个 "unsafe-chars" 是规范里定义的，会影响 HTML 本身行为的某个概念来着。

**Comment by yaniswang** [comment]
好的，问题解释清楚了，那这个issue关闭了
