### ISSUE TITLE
Feature request: Input via stdin

### ISSUE THREAD

**Issue by mmaday** [yaniswang/HTMLHint#97]
Great utility.  It'd be super handy to allow input to htmlhint via an input stream (STDIN).  jshint has implemented this by using - as the filespec (https://github.com/jshint/jshint/issues/687/).

This would allow buffers to be piped in.  I could use this in the SublimeLinter plugin I wrote for htmlhint (https://github.com/mmaday/SublimeLinter-contrib-htmlhint).  As the user edits their HTML files, the editor contents would get piped to htmlhint and linting errors would show up in realtime without the user having to save the file first.

Thanks!

**Comment by yaniswang** [comment]
Ok, next version will add this feature.

**Comment by yaniswang** [comment]
Done, please try:

	cat test.html | htmlhint stdin
