### ISSUE TITLE
Explain the format of .htmlhintrc

### ISSUE THREAD

**Issue by ricardograca** [yaniswang/HTMLHint#98]
I'm just looking into configuring htmlhint with a .htmlhintrc file and the docs don't tell me what that file should look like. It would help if there was some kind of example in the Readme or one of the wikis.

**Comment by yaniswang** [comment]
https://github.com/yaniswang/HTMLHint/wiki/Usage#about-htmlhintrc

**Comment by yaniswang** [comment]
Done, tks~

**Comment by ricardograca** [comment]
:+1: Many thanks

**Comment by jtheletter** [comment]
Updated link: https://github.com/htmlhint/HTMLHint#-configuration

**Comment by jtheletter** [comment]
Archive for above dead link: https://web.archive.org/web/20160129222029/https://github.com/yaniswang/HTMLHint/wiki/Usage

**Comment by Shinigami92** [comment]
We are currently recreating the configuration!
In v1.0.0 we plan to support such a configuration: https://github.com/htmlhint/HTMLHint/issues/279#issuecomment-417939741

The basis for this new configuration has already been created in https://github.com/htmlhint/HTMLHint/pull/445

**Comment by seisvelas** [comment]
Why was the Wiki deleted at all? There is now no extant documentation for custom rules without using waybackmachine

**Comment by Shinigami92** [comment]
> Why was the Wiki deleted at all? There is now no extant documentation for custom rules without using waybackmachine

I temporarily reopened the wiki until we were finished with the new documentation

Please note that some parts are no longer compatible or out of date

**Comment by seisvelas** [comment]
Cool, thanks! I didn't realize new docs were coming.

**Comment by Shinigami92** [comment]
Current state of the new docs can be found here: https://htmlhint.com/docs/user-guide/getting-started

And here is the wip state/branch: https://github.com/htmlhint/HTMLHint/tree/docs/configuration-structure/docs/user-guide/rules
