### ISSUE TITLE
textarea tag closing problem not detected

### ISSUE THREAD

**Issue by deepaksingh0191** [yaniswang/HTMLHint#99]
i tried htmlhint to detect error or some missing tag in html but it doesn't catched missing </textarea> at end ot <textarea>.
where i closed it as <textarea />.

**Comment by yaniswang** [comment]
Can you show a demo code?

**Comment by deepaksingh0191** [comment]
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<title>HTMLHint</title>
</head>
<body>
    <div>
    <textarea rows="4" cols="20"  class="form-control" ng-model="user.address" required />        
    </div>
</body>
</html>

**Comment by deepaksingh0191** [comment]
<textarea rows="4" cols="20"  class="form-control" ng-model="user.address" required />

**Comment by yaniswang** [comment]
textarea is not in empty elements list: https://developer.mozilla.org/en-US/docs/Glossary/Empty_element
